apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        owner: mmacanmunhoz
        repo: argo-patterns
        tokenRef:
          secretName: github-token
          key: token
      requeueAfterSeconds: 60
  template:
    metadata:
      name: 'stack-apps-{{branch_slug}}-{{number}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/mmacanmunhoz/argo-patterns.git
        targetRevision: '{{head_sha}}'
        path: 'workloads/'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'workload-{{branch_slug}}-{{number}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
