apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: argocd
type: Opaque
data:
  token: Z2l0aHViX3BhdF8xMUFLVVBOSVkwV2JFZVgza3ZIdmtBX2huREZIQ0RVbkJFNWw0bTZGY21BaGpOR0Vkd251NEtNeU15bXRmQUhKVmo2VFhIUk5PTElaNmVIZHBKCg==
