apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx-deployment
  labels:
    app: {{ .Release.Name }}-nginx
spec:
  replicas: {{ .Values.randomLogger.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.nginx.image }}
        ports:
        - containerPort: {{ .Values.nginx.port }}
        imagePullPolicy: {{ .Values.nginx.imagePullPolicy }}